### ISSUE TITLE
Attempted to assign to readonly propety fail

### ISSUE THREAD

**Issue by UgrBs** [OpenVidu/openvidu-tutorials#141] opened 2020-11-24 08:41 UTC
![resim_2020-11-24_114024](https://user-images.githubusercontent.com/11991337/100069455-d7074400-2e49-11eb-8541-2fac80f01412.png)

When i run the tutorial i get the error:typeerror attempted to assign to readonly property. I have openvidu react-native licence. Could you please guide me how can i run the tutorial correctly

Version: openvidu-react-native-adapter-2.16.0.tgz

**Comment by CSantosM** [comment] 2020-11-24 16:14
Hi, thanks for your report. 

We have discovered that we have a bug because of the Typescript updated (> 4.0). 
The problem is related with this [Typescript issue](https://github.com/microsoft/tslib/issues/103). When typescript transpile the TS code to JS, it assumes the exports as readonly and the openvidu-react-native-adapter can't do his job. 

We're working on fix this issue as soon as possible.

**Comment by IVTore** [comment] 2020-11-24 17:03
Hi, @UgrBs is in our Feta Bilgisayar Team and we already use OpenVidu 2.15.0 server . We are about to show our customers a demonstration this Friday. If the process of fixing the bug will take a while, can you send us the previous version?

**Comment by CSantosM** [comment] 2020-12-01 13:20
Fixed on react-native-adapter 2.16.1

**Closed by CSantosM** 2020-12-01 13:20 UTC
Labels: bug
