### ISSUE TITLE
Importing OpenviduSessionModule cause problem with rendering app

### ISSUE THREAD

**Issue by b3hz4d** [OpenVidu/openvidu-tutorials#75] opened 2020-01-28 13:16 UTC
When I import OpenviduSessionModule in my app.module.ts, angular rendering OpenVidu not my app on routes

`
import { OpenviduSessionModule } from 'openvidu-angular';
`
I followed docs from here https://openvidu.io/docs/tutorials/openvidu-library-angular/

**Comment by ivanlunardi** [comment] 2020-03-18 16:47
me too

**Comment by CSantosM** [comment] 2020-04-11 21:12
Hello,

We’re working on get better angular library. 
Could you tell us how to reproduce this issue?

**Comment by ivanlunardi** [comment] 2020-04-14 07:39
hi,
the problem is the "router" inside the module , because it respond at every route ,  /<everrything>
the solution i found is, to use components instead of the whole module

**Comment by CSantosM** [comment] 2020-04-15 09:52
Hello, 

We just fixed this issue in this [commit](98ff45251e73d054452ade397a4d6e6ba49f4e82) .
This will be included in the next release (2.13.0). 
Thank you for report.

Regards

**Closed by CSantosM** 2020-04-15 09:52 UTC
Labels: bug
